{
 "title": "Healthra Application Dashboard",
 "tags": [
  "healthra",
  "eks"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU Usage (healthra)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"healthra\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage (healthra)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"healthra\",container!=\"\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Django HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(django_http_requests_before_losses_total[1m])) by (view)",
     "legendFormat": "{{view}}"
    }
   ]
  },
  {
   "title": "Django Database Queries Active",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(django_db_queries_total[1m]))",
     "legendFormat": "Queries/sec"
    }
   ]
  }
 ]
}